2025-08-24 11:02:38,289 - INFO - --- Starting On-Demand Log Processor ---
2025-08-24 11:02:38,290 - INFO - Found 2 new log file(s): SESSION_LOG_2025-08-24_10-30-25.json, SESSION_LOG_2025-08-24_10-30-31.json
2025-08-24 11:02:38,290 - INFO - 
--- Processing: SESSION_LOG_2025-08-24_10-30-25.json ---
2025-08-24 11:02:38,290 - INFO - Running calculation for SESSION_LOG_2025-08-24_10-30-25.json...
2025-08-24 11:02:39,191 - INFO - Error running calculation program: Command '['python', 'C:\\Users\\Charging\\CHARGING\\LOCAL_TO_CLOUD\\calculate_bill.py', 'C:\\Users\\Charging\\CHARGING\\ChargeSOM_LOGS\\Session_Logs\\SESSION_LOG_2025-08-24_10-30-25.json']' returned non-zero exit status 1.
2025-08-24 11:02:39,193 - INFO - Uploading SESSION_LOG_2025-08-24_10-30-25.json to configured repository...
2025-08-24 11:02:39,813 - INFO -  - Upload successful.
2025-08-24 11:02:41,197 - INFO -  - Successfully processed and logged SESSION_LOG_2025-08-24_10-30-25.json.
2025-08-24 11:02:41,197 - INFO - 
--- Processing: SESSION_LOG_2025-08-24_10-30-31.json ---
2025-08-24 11:02:41,197 - INFO - Running calculation for SESSION_LOG_2025-08-24_10-30-31.json...
2025-08-24 11:02:41,947 - INFO - Error running calculation program: Command '['python', 'C:\\Users\\Charging\\CHARGING\\LOCAL_TO_CLOUD\\calculate_bill.py', 'C:\\Users\\Charging\\CHARGING\\ChargeSOM_LOGS\\Session_Logs\\SESSION_LOG_2025-08-24_10-30-31.json']' returned non-zero exit status 1.
2025-08-24 11:02:41,947 - INFO - Uploading SESSION_LOG_2025-08-24_10-30-31.json to configured repository...
